version: '3'

services:
  mysql:
    image: mysql:8
    container_name: symfony_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - 3306:3306

    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf5
      MYSQL_USER: sf5
      MYSQL_PASSWORD: sf5

  api:
    build:
      context: ./
    container_name: symfony_api
    volumes:
      - ./:/var/www
    ports:
    - 8080:80

